name: JLib
main: com.j0ach1mmall3.jlib.Main
version: 4.12.0
author: j0ach1mmall3
description: Main Library for j0ach1mmall3 Plugins
softdepend: [Vault, PlaceholderAPI, ProtocolSupport, ProtocolLib]
commands:
    JDebug:
        description: Debug Command
        usage: /<command>
permissions:
    jlib.debug:
        description: Access to /jdebug
        default: op